### Site Settings ###
title               : Elias Yilma
description         : >-                               # >- means to ignore newlines until "url:"
                      I'm an engineer/programmer who's passionate 
                      about machine learning and Artificial Intelligence.

url                 : "eliasyilma.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : ""                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Elias Yilma
  image             : https://i.pinimg.com/564x/c1/11/7b/c1117b0d2272e7b9ee37fae25f818b8b.jpg
#  behance           : your_username
# dribbble          : your_username
  email             : eliasyilmat2@gmail.com
#  facebook          : your_username
  github            : eliasyilma
# gitlab            : your_username
# instagram         : your_username
  linkedin          : eliasyilma
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
